version: '2'
services:

  mongodb:
    image: mongo:latest
    container_name: vehicle-db
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/2C_vehicle_db"
    networks:
      - vehicle-db




volumes:
   mongodata:

networks:
  vehicle-db:
